// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `migrate`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Database>>
abstract class Database implements RustOpaqueInterface {
  /// Get all ships from the database
  Future<List<Ship>> getAllShips();

  /// Get distinct manufacturers
  Future<List<String>> getAvailableManufacturers();

  /// Get distinct sizes
  Future<List<String>> getAvailableSizes();

  /// Get a single ship by ID
  Future<Ship?> getShipById({required String id});

  /// Check if the database has any ships
  Future<bool> hasShips();

  /// Import ships from bundled JSON into SQLite
  Future<PlatformInt64> importShips({required String json});

  /// Open or create the database at the given path, run migrations
  static Future<Database> open({required String path}) =>
      RustLib.instance.api.crateApiDatabaseDatabaseOpen(path: path);

  /// Search ships by query and size filter
  Future<List<Ship>> searchShips({
    required String query,
    required String sizeFilter,
    required String manufacturerFilter,
  });

  /// Total ship count
  Future<PlatformInt64> shipCount();
}
