// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ShipImport`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

/// A ship from the Star Citizen database
class Ship {
  final String id;
  final String name;
  final String slug;
  final String manufacturer;
  final String classification;
  final String focus;
  final int crewMin;
  final int crewMax;
  final double cargo;
  final double pledgePrice;
  final double maxSpeed;
  final String size;
  final String description;

  const Ship({
    required this.id,
    required this.name,
    required this.slug,
    required this.manufacturer,
    required this.classification,
    required this.focus,
    required this.crewMin,
    required this.crewMax,
    required this.cargo,
    required this.pledgePrice,
    required this.maxSpeed,
    required this.size,
    required this.description,
  });

  Future<String> cargoLabel() =>
      RustLib.instance.api.crateApiModelShipCargoLabel(that: this);

  Future<String> crewLabel() =>
      RustLib.instance.api.crateApiModelShipCrewLabel(that: this);

  Future<String> pledgePriceLabel() =>
      RustLib.instance.api.crateApiModelShipPledgePriceLabel(that: this);

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      slug.hashCode ^
      manufacturer.hashCode ^
      classification.hashCode ^
      focus.hashCode ^
      crewMin.hashCode ^
      crewMax.hashCode ^
      cargo.hashCode ^
      pledgePrice.hashCode ^
      maxSpeed.hashCode ^
      size.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Ship &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          slug == other.slug &&
          manufacturer == other.manufacturer &&
          classification == other.classification &&
          focus == other.focus &&
          crewMin == other.crewMin &&
          crewMax == other.crewMax &&
          cargo == other.cargo &&
          pledgePrice == other.pledgePrice &&
          maxSpeed == other.maxSpeed &&
          size == other.size &&
          description == other.description;
}
